


SELECT BOARD_NO, BOARD_GROUP, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE
    	FROM BOARD
    	WHERE BOARD_CATEGORY = '0'
    	ORDER BY BOARD_NO DESC;
    	

SELECT BOARD_NO, BOARD_ID, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE
FROM BOARD;
-- 일반 글 작성
INSERT INTO BOARD
VALUES(board_seq.nextval,boardgroup_seq.nextval,1,#{id},#{title},#{content},0,sysdate)


-- 답글 작성
UPDATE BOARD
SET BOARD_GROUP = BOARD_GROUP+1
WHERE BOARDGROUP_NO = (SELECT BOARDGROUP_NO FROM BOARD WHERE BOARD_NO = #{board_no})
AND BOARD_GROUP > (SELECT BOARD_GROUP FROM BOARD WHERE BOARD_NO = #{board_no})

INSERT INTO BOARD
VALUES(BOARD_SEQ.NEXTVAL,
(SELECT BOARDGROUP_NO FROM BOARD WHERE BOARD_NO=#{BOARD_NO}),
(SELECT BOARD_GROUP+1 FROM BOARD WHERE BOARD_NO=#{BOARD_NO})
,#{BOARD_ID},#{TITLE},#{CONTENT},0,SYSDATE)